name: ng_di_example
version: 0.0.1
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  ng_di:
    path: ../
dev_dependencies:
  build_runner: any
  test: any
  build_test: any
  build_web_compilers: any
