= ng_di

image:https://travis-ci.org/dart-league/ng_di.svg?branch=master["Build Status", link="https://travis-ci.org/dart-league/ng_di"]

A Dependency Injection package taken from angular DI.

== Usage

Create one of the examples shown below

== Inject by Type

Create an Injector by using annotation `@GenerateInjector` and pass the List of types, then the generator will create the respective injector.

[source,dart]
----
include::example/type.dart[tag=injector]
----

Full code:

[source,dart]
----
include::example/type.dart[tag=*]
----

== Inject using `@Inject()` annotation

In this case you can specify the token corresponding to the dependency that will be injected. For example:

[source,dart]
----
include::example/inject.dart[]
----

== Inject using `@Optional()` or `@optional` annotation

In this case we can mark dependencies as optional, so if the value is not injected then a null value is passed. For example:

[source,dart]
----
include::example/optional.dart[]
----

== Inject using `@Self()` or `@self` annotation

In this case we can mark dependencies as self, so the injector should retrieve a dependency only from itself. For
 example:

[source,dart]
----
include::example/self.dart[]
----

== Inject using `@SkipSelf()` or `@skipSelf` annotation

In this case we can mark dependencies as optional, so the dependency resolution should start from the parent injector. For example:

[source,dart]
----
include::example/skip_self.dart[]
----