targets:
  $default:
    builders:
      ng_di:
        generate_for: [example/**, test/**]
builders:
  ng_di:
    import: package:ng_di/builder.dart
    builder_factories: [builder]
    auto_apply: dependents
    build_extensions:
      .dart: [.ng_di.g.part]
    applies_builders: [source_gen|combining_builder]
