builders:
  built_mirrors_builder:
    target: :_ng_di
    import: package:ng_di/builder.dart
    builder_factories: [builder]
    build_to: source
    auto_apply: root_package
    build_extensions:
      .dart: [.g.dart]