name: ng_di
description: Dependency injection package taken from angular DI.
version: 0.0.1+1
homepage: https://github.com/dart-league/ng_di
author: Luis vargas <luisvargastijerino@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  built_mirrors: ^0.5.0
  meta: ^1.1.1
  logging: ^0.11.3+1
  build_runner: ^0.4.0

dev_dependencies:
  test: ^0.12.0
