name: ng_di
description: Dependency injection package taken from angular DI.
version: 2.0.0-alpha
homepage: https://github.com/dart-league/ng_di
author: Luis vargas <luisvargastijerino@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ">=0.36.0 <1.0.0"
  build: ^1.1.6
  source_gen: ^0.9.1
  angular: ^6.0.0-alpha
#  angular:
#    git:
#      url: git://github.com/dart-lang/angular.git
#      path: angular


dev_dependencies:
  build_runner: any
  build_test: any
  test: ^1.0.0
