name: ng_di
description: Dependency injection package taken from angular DI.
version: 1.0.0
homepage: https://github.com/dart-league/ng_di
author: Luis vargas <luisvargastijerino@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: ^0.32.5
  build: ^0.12.7
  source_gen: ^0.9.1
  angular: ^5.0.0
#  angular:
#    git:
#      url: git://github.com/dart-lang/angular.git
#      path: angular


dev_dependencies:
  build_runner: ^0.10.0
  build_test: any
  test: ^1.0.0
